export const Routes = {
  Home: "Home",
  Registration: "Registration",
  LogIn: "LogIn",
  Stack: "Stack",
  Tab: "Tab",
  ServiceRequestDetails: "ServiceRequestDetails",
  NotificationDetails: "NotificationDetails",
  RepairFlow: "RepairFlow",
  ScheduleServiceScreen: "ScheduleServiceScreen",
  ScheduleScreen: "ScheduleScreen",
  PaymentScreen: "PaymentScreen",
  PaymentResultScreen: "PaymentResultScreen",
  ContactInformation: "ContactInformation",
};
